# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
        name: production
    permissions:
      contents: write
    steps:

      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          
          filename: general.svg
          output_action: gist
          committer_gist: fb75b98207af1286b655aa2ef1ef2386

          # Options
          user: 360NENZ
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          commits_authoring: 360NENZ, gdgwhy@outlook.com, 2831218066@qq.com, i@360nenz.top, 51311642+360NENZ@users.noreply.github.com, 12966440-360NENZ@users.noreply.gitlab.com
          config_timezone: Asia/Shanghai

          # Code Habits return "Unexpected error", disabled
          #plugin_habits: yes
          #plugin_habits_charts_type: classic
          #plugin_habits_days: 14
          #plugin_habits_facts: yes
          #plugin_habits_from: 200
          #plugin_habits_languages_limit: 8
          #plugin_habits_languages_threshold: 0%

          plugin_introduction: yes
          plugin_introduction_title: yes

          # Language Part
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          repositories_affiliations: owner, collaborator
          #repositories_batch: 200
          repositories_forks: yes

# Test completed, disabled
#      - name: Metrics workflow form ZianTT (Test)
#        uses: lowlighter/metrics@latest
#        with:
#          token: ${{ secrets.METRICS_TOKEN }}
#          filename: from_ziantt.svg
#          output_action: gist
#          committer_gist: fb75b98207af1286b655aa2ef1ef2386
#          user: 360NENZ
#          base: header, activity, community, repositories, metadata
#          config_timezone: Asia/Shanghai
#          plugin_introduction: yes
#          plugin_languages: yes
#          plugin_languages_colors: github
#          plugin_languages_limit: 8
#          plugin_languages_details: lines, percentage
#          plugin_languages_indepth: yes
#          plugin_languages_analysis_timeout: 30
#          repositories_affiliations: collaborator
#          commits_authoring: 360NENZ, gdgwhy@outlook.com, 2831218066@qq.com, i@360nenz.top, 51311642+360NENZ@users.noreply.github.com, 12966440-360NENZ@users.noreply.gitlab.com
#          plugin_habits: yes
#          plugin_habits_facts: yes

# Achievement return "Unexpected error", disabled
#      - name: Achievements
#        if: ${{ success() || failure() }}
#        uses: lowlighter/metrics@latest
#        with:
#          filename: achievements.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          output_action: gist
#          committer_gist: fb75b98207af1286b655aa2ef1ef2386
#          plugin_achievements: yes
#          plugin_achievements_display: compact #or detailed
#          #plugin_fortune: yes
#          plugin_achievements_secrets: yes
#          #plugin_achievements_threshold: C

      - name: People & Star
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: people_star.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: fb75b98207af1286b655aa2ef1ef2386
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Star Part
          plugin_stars: yes
          plugin_stars_limit: 4

          # Starlist Part
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes

# Activity return "Unexpected error", disabled
#      - name: Activity
#        if: ${{ success() || failure() }}
#        uses: lowlighter/metrics@latest
#        with:
#          filename: activity.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          output_action: gist
#          committer_gist: fb75b98207af1286b655aa2ef1ef2386
#          plugin_activity: yes
#          plugin_activity_days: 14
#          plugin_activity_filter: all
#          plugin_activity_limit: 5
#          plugin_activity_load: 300
#          plugin_activity_timestamps: yes
#          plugin_activity_visibility: all

# Difficult to place,disable
#      - name: Language
#        if: ${{ success() || failure() }}
#        uses: lowlighter/metrics@latest
#        with:
#          filename: language.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          output_action: gist
#          committer_gist: fb75b98207af1286b655aa2ef1ef2386
#          plugin_languages: yes
#          plugin_languages_analysis_timeout: 15
#          plugin_languages_analysis_timeout_repositories: 7.5
#          plugin_languages_categories: markup, programming
#          plugin_languages_colors: github
#          plugin_languages_limit: 8
#          plugin_languages_recent_categories: markup, programming
#          plugin_languages_recent_days: 14
#          plugin_languages_recent_load: 300
#          plugin_languages_sections: most-used
#          plugin_languages_threshold: 0%

# Difficult to place,disable
#      - name: Star
#        if: ${{ success() || failure() }}
#        uses: lowlighter/metrics@latest
#        with:
#          filename: star.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          output_action: gist
#          committer_gist: fb75b98207af1286b655aa2ef1ef2386
#          plugin_stars: yes
#          plugin_stars_limit: 4

          # Starred topics return empty, disabled
          #plugin_topics: yes
          #plugin_topics_limit: 15
          #plugin_topics_mode: starred
          #plugin_topics_sort: stars